version: "3.3"

services:
    api:
        build: ./api-docker
        restart: always
        env_file:
            - api.env
        volumes: 
            - ./api-etc:/api
        ports:
            - "${API_PORT:-20000}:${API_PORT:-20000}"
        networks:
            backend:
                aliases:
                    - ${API_ALIAS:-api}
    motion:
        build: ./motion-docker
        restart: always
        env_file:
            - motion.env
        volumes: 
            - ./motion-etc:/usr/local/etc/motion
            - ./rclone-etc:/root/.config/rclone
            - motion-data:/var/lib/motion
            - motion-log:/var/log/motion
        ports:
            - "${MOTION_ADMIN_PORT:-8080}:${MOTION_ADMIN_PORT:-8080}"
            - "${MOTION_ADMIN_PORT:-8081}:${MOTION_ADMIN_PORT:-8081}"
        networks:
            backend:
                aliases:
                    - ${MOTION_ALIAS:-motion}
        devices:
            - /dev/video0:/dev/video0
            - /dev/snd
volumes:
    motion-data:
    motion-log:
networks:
    backend:
