#!/usr/bin/env sh

WCM_ID=${MOTION_ALIAS:-$(hostname)}
echo "Start motion($WCM_ID) at $(date -u +%Y-%m-%d_%H:%M)"

if [ ! -f /usr/local/etc/motion/motion.conf ]; then
    cp -f /usr/local/etc/motion-dist/motion.conf /usr/local/etc/motion/motion.conf
fi 

/usr/local/bin/motion -n
